### ISSUE TITLE
no documentation on agent installation?

### ISSUE THREAD

**Issue by elric77** [Axway/ats-framework#14]
Cool framework!  Unfortunately I can't find any documentation about installing the agent on remote Axway products.  Any idea how to do this on say, B2Bi?  Thanks.

**Comment by svilen-d** [comment]
Hello and thank you for your interest!
Documentation for the ATS Agent (including installation) is available here - https://axway.github.io/ats-framework/The-ATS-Agent.html. It could be installed standalone or generally in any Web server having Java Servlet Container (like Tomcat).
If you you have other considerations or feedback - please, list them. You may also contact us via our mail list _ats.team (at) axway.com_
Regards,
Svilen

**Comment by elric77** [comment]
Great thanks!  That is what I was looking for.
